<?php

namespace App\Controller\Admin;

use App\Entity\Docequipes;
use App\Form\VichFilesField;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\ChoiceField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateTimeField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IntegerField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;


class DocequipesCrudController extends AbstractCrudController
{
    private ParameterBagInterface $params;

    public function __construct(ParameterBagInterface $params)
    {
        $this->params = $params;
    }


    public static function getEntityFqcn(): string
    {
        return Docequipes::class;
    }
    public function configureActions(Actions $actions): Actions
    {
        return $actions->update('index', Action::EDIT, function  (Action $action) {
            return $action->setIcon('fa fa-pencil-alt')->setLabel(false);})
            ->update('index', Action::DELETE, function  (Action $action) {
                return $action->setIcon('fa fa-trash-alt')->setLabel(false);}); // TODO: Change the autogenerated stub
    }
    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->showEntityActionsInlined()
            ->overrideTemplates(['crud/index'=> 'bundles/EasyAdminBundle/indexEntities.html.twig', ])
            ->setEntityLabelInSingular('Docequipes')
            ->setEntityLabelInPlural('Docequipes')
            ->setPageTitle(Crud::PAGE_INDEX, '<h2>Les documents à télécharger</h2>')
            ->setPageTitle(Crud::PAGE_EDIT, 'Editer le document')
            ->setPageTitle(Crud::PAGE_NEW, 'Nouveau document')
            ->setSearchFields(['id', 'fichier', 'type', 'titre', 'description'])
            ->setPaginatorPageSize(10);
    }


    public function configureFields(string $pageName): iterable
    {
        $type = ChoiceField::new('type')->setChoices(['Zip' => 'zip', 'pdf' => 'pdf', 'doc' => 'doc','excel'=>'excel']);
        $titre = TextField::new('titre');
        $description = TextField::new('description');
        $fichierFile = VichFilesField::new('fichierFile')->setBasePath($this->params->get('app.path.docequipes.localhost'));
        $id = IntegerField::new('id', 'ID');
        $fichier = TextField::new('fichier')->setTemplatePath('bundles\\EasyAdminBundle\\liste_docequipes.html.twig');
        $concours = ChoiceField::new('concours')->setChoices(['' => '', 'CIA' => 'CIA', 'CN' => 'CN']);
        $updatedAt = DateTimeField::new('updatedAt');
        $updatedat = DateTimeField::new('updatedAt', 'Mis à jour  le ');

        if (Crud::PAGE_INDEX === $pageName) {
            return [$type, $titre, $description, $fichier, $concours, $updatedat];
        } elseif (Crud::PAGE_DETAIL === $pageName) {
            return [$id, $fichier, $updatedAt, $type, $titre, $concours, $description];
        } elseif (Crud::PAGE_NEW === $pageName) {
            return [$type, $titre, $description, $concours, $fichierFile];
        } elseif (Crud::PAGE_EDIT === $pageName) {
            return [$type, $titre, $description, $concours, $fichierFile];
        }
    }


    public function updateEntity(EntityManagerInterface $entityManager, $entityInstance): void
        {   $date = new DateTime('now');
            $entityInstance->setUpdatedAt($date);
            parent::persistEntity($entityManager, $entityInstance); // TODO: Change the autogenerated stub
        }
}
