<?php

namespace App\Controller\Aide;

use AllowDynamicProperties;
use App\Controller\OdpfAdmin\AdminCKEditorField;
use App\Entity\AideEnLigne;
use App\Entity\CategorieAide;
use App\Entity\SousCategorieAide;
use App\Form\ArticleAideType;
use App\Form\OdpfSouscategorieType;
use App\Form\SouscategorieAideType;
use App\Repository\CategorieAideRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\QueryBuilder;
use Doctrine\Persistence\ManagerRegistry;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\ArrayField;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ChoiceField;
use EasyCorp\Bundle\EasyAdminBundle\Field\CollectionField;
use EasyCorp\Bundle\EasyAdminBundle\Field\Field;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;


class AideEnLigneCrudController extends AbstractCrudController
{


    private ManagerRegistry $doctrine;

    public function __construct(ManagerRegistry $doctrine){

        $this->doctrine = $doctrine;
    }
    public static function getEntityFqcn(): string
    {
        return AideEnLigne::class;
    }
    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->showEntityActionsInlined()
            ->overrideTemplates(['crud/index'=> 'bundles/EasyAdminBundle/indexEntities.html.twig', ])
            ->addFormTheme('@FOSCKEditor/Form/ckeditor_widget.html.twig')
            ->setPageTitle('index', 'Articles de l\'aide en ligne')
            ->setPaginatorPageSize(100);
    }

        public function configureFields(string $pageName): iterable
    {
        $qb=$this->doctrine->getRepository(SousCategorieAide::class)->createQueryBuilder('a');
        $souscategories=$this->doctrine->getRepository(SousCategorieAide::class)->findAll();
        return [
            yield TextField::new('titre', 'Titre'),
            //yield AssociationField::new('sousCategorie','Sous-catégorie'),
            yield CollectionField::new('souscategorie','Sous catégorie')->onlyOnIndex(),
            yield CollectionField::new('souscategorie')
                ->setEntryType(EntityType::class)
                ->setFormTypeOptions([
                    'entry_options' => [
                        'class'=>SousCategorieAide::class,
                        'choice_label'=>'intitule'],
                    'required' => false,
                ])
                ->renderExpanded()
                ->onlyOnForms(),
            yield AdminCKEditorField::new('texte'),
            yield ChoiceField::new('permission')->setChoices([
                'ROLE_SUPER_ADMIN' => 'ROLE_SUPER_ADMIN',
                'ROLE_ADMIN' => 'ROLE_ADMIN',
                'ROLE_COMITE' => 'ROLE_COMITE',
                'ROLE_PROF' => 'ROLE_PROF',
                'ROLE_JURY' => 'ROLE_JURY',
                'ROLE_JURYCIA' => 'ROLE_JURYCIA',
                'ROLE_ORGACIA' => 'ROLE_ORGACIA',
            ])


        ];
    }
    public function persistEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        parent::persistEntity($entityManager, $entityInstance); // TODO: Change the autogenerated stub
    }
    public function configureActions(Actions $actions): Actions{
        return $actions->update('index', Action::DELETE,function  (Action $action) {
            return $action->setIcon('fa fa-trash-alt')->setLabel(false);}
        )
            ->update('index', Action::EDIT,function  (Action $action) {
                return $action->setIcon('fa fa-pencil-alt')->setLabel(false);}
            );
    }





}
